service: panopticon
frameworkVersion: "=1.26.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  executor:
    handler: handler.executor
    events:
      - http: GET executor
